Update anchore-syft2.yml
Added verification section for troubleshooting purpose.

Signed-off-by: Yoky <yt2278@nyu.edu>

diff --git a/.github/workflows/anchore-syft2.yml b/.github/workflows/anchore-syft2.yml
--- a/.github/workflows/anchore-syft2.yml
+++ b/.github/workflows/anchore-syft2.yml
@@ -60,6 +60,9 @@ jobs:
           }
         }' > attestation_predicate.json
 
+    - name: Validate JSON
+      run: jq . attestation_predicate.json || echo "Invalid JSON"
+
     - name: Display Attestation Predicate
       run: cat attestation_predicate.json  # Print to verify JSON format
 
