Update SecretScan_TruffleHog2.yml
Signed-off-by: Yoky <yt2278@nyu.edu>

diff --git a/.github/workflows/SecretScan_TruffleHog2.yml b/.github/workflows/SecretScan_TruffleHog2.yml
--- a/.github/workflows/SecretScan_TruffleHog2.yml
+++ b/.github/workflows/SecretScan_TruffleHog2.yml
@@ -34,13 +34,15 @@ jobs:
         id: check-secrets
         run: |
           #if [ $? -ne 0 ]; then
-          if [ -s found_secrets.txt ]; then
+          if [ -s found_secrets.txt ]; then        # Check if found_secrets.txt is not empty
             echo "Secrets found in the repository!"
-            echo "status=fail" >> $GITHUB_ENV
-            cat found_secrets.txt  # Print paths of found secrets
-            exit 1
+            echo "status=fail" >> $GITHUB_ENV       # Set status to fail in the environment
+            cat found_secrets.txt                    # Print paths of found secrets
+            exit 1                                   # Exit with error status
           else
             echo "No secrets found."
+            echo "status=success" >> $GITHUB_ENV     # Set status to success in the environment
+  
             echo "status=success" >> $GITHUB_ENV
           fi
 
