Update SecretScan_TruffleHog2.yml
Signed-off-by: Yoky <yt2278@nyu.edu>

diff --git a/.github/workflows/SecretScan_TruffleHog2.yml b/.github/workflows/SecretScan_TruffleHog2.yml
--- a/.github/workflows/SecretScan_TruffleHog2.yml
+++ b/.github/workflows/SecretScan_TruffleHog2.yml
@@ -3,7 +3,7 @@ name: Secret Scan2
 on:
   push:
     branches: '**'  # all branches
-      
+
   pull_request:
     branches:
       - main
@@ -24,18 +24,22 @@ jobs:
 
       - name: Run TruffleHog
         id: trufflehog
-        run: trufflehog --regex . || true          # Scan all folders and files
+        run: |
+          # Run TruffleHog and capture output and error
+          output=$(trufflehog --regex --json . 2>&1) || true
+          echo "$output" > secrets.json                  # Save full output to secrets.json for debugging
+          echo "$output" | jq -r '.[] | .path' > found_secrets.txt || true  # Extract file paths of found secrets
 
       - name: Check for secrets
         id: check-secrets
         run: |
-          if [ $? -ne 0 ]; then
+          if [ -s found_secrets.txt ]; then              # Check if found_secrets.txt is not empty
             echo "Secrets found in the repository!"
-            echo "status=fail" >> $GITHUB_ENV
-            exit 1
+            echo "status=fail" >> $GITHUB_ENV             # Set status to fail in the environment
+            cat found_secrets.txt                          # Print paths of found secrets
           else
             echo "No secrets found."
-            echo "status=success" >> $GITHUB_ENV
+            echo "status=success" >> $GITHUB_ENV           # Set status to success in the environment
           fi
 
       - name: Set commit status
@@ -43,4 +47,4 @@ jobs:
           curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
-          -d "{\"state\": \"${{ env.status }}\", \"context\": \"Secret Scan\"}"
+          -d "{\"state\": \"${{ env.status }}\", \"context\": \"Secret Scan\"}"  # Set commit status based on found secrets
