Update SecretScan_TruffleHog.yml
Revised to output status to ruleset.

Signed-off-by: Yoky <yt2278@nyu.edu>

diff --git a/.github/workflows/SecretScan_TruffleHog.yml b/.github/workflows/SecretScan_TruffleHog.yml
--- a/.github/workflows/SecretScan_TruffleHog.yml
+++ b/.github/workflows/SecretScan_TruffleHog.yml
@@ -49,6 +49,8 @@ jobs:
           if [ -s trufflehog-report.json ]; then
             echo "Secrets found! See trufflehog-report.json for details."
             echo "status=fail" >> $GITHUB_ENV
+            exit 1  # This will fail the job
+            
           else
             echo "No secrets found."
             echo "status=success" >> $GITHUB_ENV
@@ -59,4 +61,5 @@ jobs:
           curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
           -H "Accept: application/vnd.github.v3+json" \
           https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
+          -d "{\"state\": \"${{ env.status }}\", \"context\": \"Secret Scan\"}"
           -d "{\"state\": \"${{ env.status }}\", \"context\": \"Secret Scan\"}"
